React
wolox-training/mdt-react pull request #14
Opened 2018-11-09 19:01 UTC by manutuero

### Summary
I modify and make it passes the Jest tests of Spread Operator.

### Trello Card
https://trello.com/c/d4cUZuWV

### Screenshot
![spread-op-tests-passed](https://user-images.githubusercontent.com/11902162/48282452-7b231b80-e438-11e8-81c9-0ca366bc37ed.png)

2018-11-12 18:11 UTC, LucasZibell requested changes

2018-11-12 18:11 UTC, LucasZibell commented on finger_exercises/ecmascript/01 - spread/index.js
> +};
Instead of copying the whole object. Why don´t you use directly the obj. Like this.
```
export const filterAttribs = ({a,b, ...obj }) => obj;
```

2018-11-12 18:11 UTC, LucasZibell commented on finger_exercises/ecmascript/01 - spread/index.js
> +  }
unnecessary curly braces

2018-11-12 18:11 UTC, LucasZibell commented on finger_exercises/ecmascript/01 - spread/utils.js
>  }
Use arrow function for this and change the order of the ternary to avoid having `!`

2018-11-12 18:11 UTC, LucasZibell commented on finger_exercises/ecmascript/01 - spread/utils.js
>  }
Furthermore you don't need a ternary for this you can use the `&&`

`possibleArray && possibleArray.isArray`

And use the property inArray o know if it is an array

2018-11-12 19:09 UTC, manutuero commented on finger_exercises/ecmascript/01 - spread/index.js
> +};
You're right! I had not thought of it.

2018-11-12 19:21 UTC, manutuero commented on finger_exercises/ecmascript/01 - spread/index.js
> +  }
I included the keys because eslint suggested it to me. Now I remove them.

2018-11-13 13:33 UTC, LucasZibell requested changes

2018-11-13 13:33 UTC, LucasZibell commented on finger_exercises/ecmascript/01 - spread/utils.js
> +export const isArray = aPossibleArray => aPossibleArray && Array.isArray(aPossibleArray);
I think you can remove the eslint disable and export it default like this
`export default aPossibleArray => aPossibleArray && Array.isArray(aPossibleArray);`

2018-11-13 14:31 UTC, LucasZibell approved these changes

2018-11-13 14:39 UTC, merged