Tech
wolox-training/mdt-react pull request #5
Opened 2018-11-02 18:29 UTC by manutuero

### Summary

I add a `technology` component and his styles to the project.

2018-11-02 18:39 UTC, SKOLZ requested changes

2018-11-02 18:39 UTC, SKOLZ commented on index.html
> +        <h4 class="tech-name">ReactJS</h4>
h3 is "more important" than h4 and since the tech name is more important than the tech release, this should be an h3 and the tech release an h4

2018-11-02 18:39 UTC, SKOLZ commented on index.html
> +    <div class="tech-border">
this border can be done using a pseudo element in the tech.

2018-11-02 18:39 UTC, SKOLZ commented on index.html
> +      <div class="tech-border tech-content">
this is the only child of its parent, most of the time when this happens it means you are adding an extra unnecessary div. you can use the `tech` div for this.

2018-11-02 18:39 UTC, SKOLZ commented on index.html
> +  <div name="tech" class="m-left-10">
divs don't use the name attribute, you should add this as a class. the `m-left-10` although is a good practice, we'll add it when we create the layout. That way we'll verify that `10` is really what we want.

2018-11-02 18:39 UTC, SKOLZ commented on scss/tech.scss
> +  position: absolute;
you don't have to use position absolute in every element inside of the tech and move it around with top and left values. you should use a column flex layout and let the elements adapt to this layout.

2018-11-05 13:11 UTC, CarlosHWolox commented
Screenshots are needed to help visualize the changes made on the PR.
Use this to make the PR.
------
## Summary

## Screenshots

## Trello Card

----

2018-11-05 13:15 UTC, CarlosHWolox commented on scss/tech.scss
> +    content: ' ';
Delete the space

2018-11-05 13:15 UTC, CarlosHWolox commented on scss/tech.scss
> +  padding: 0 10px 10px 0;
Why adding this padding? Should be the same for both sides and top-bottom.

2018-11-05 13:15 UTC, CarlosHWolox commented on scss/tech.scss
> +    font-size: 15px;
There are predefined font sizes already, use them as variables.

2018-11-05 13:15 UTC, CarlosHWolox commented on scss/tech.scss
> +  flex-wrap: wrap;
Why using wrap?

2018-11-05 13:15 UTC, CarlosHWolox commented on scss/tech.scss
> +    height: 100px;
Same here, there are already defined sizes, look on the trello cards and use them as variables.

2018-11-05 15:29 UTC, CarlosHWolox commented on scss/colors.scss
> +$earls-green: #BED23C;
Add all the colors that are indicated on this trello card, aswell as the sizes: https://trello.com/c/qp5nMqvV/11-setup-del-proyecto

2018-11-05 15:29 UTC, CarlosHWolox commented on scss/titles.scss
> +  padding: 38px 0 0 52px;
remember we use margin to separate from other content, i think here you could do a better use of the position of the element ::before setting the top and left and not changing here the padding, better is to use the margin here to control both elements separations of outside elements.

2018-11-05 17:15 UTC, CarlosHWolox approved these changes

2018-11-05 17:18 UTC, SKOLZ approved these changes

2018-11-05 17:19 UTC, merged